Package.json reference fails when building with serverless package
```
➜ yarn workspace @..../.... serverless package

yarn workspace v1.22.17
yarn run v1.22.17
$ /..../..../..../..../node_modules/.bin/serverless package
Serverless: serverless-offline-ssm checking serverless version 2.72.2.
Serverless: Cleaning dependency symlinks
Serverless: Creating dependency symlinks
Serverless: Compiling to es2018 bundle with esbuild...
Serverless: Compiling with concurrency: Infinity
✘ [ERROR] Could not resolve "../../package.json"

    ../node_modules/sequelize/lib/sequelize.js:571:19:
      571 │     return require("../../package.json").version;
          ╵                    ~~~~~~~~~~~~~~~~~~~~

 
 Error ---------------------------------------------------
 
  Error: Build failed with 1 error:
  ../node_modules/sequelize/lib/sequelize.js:571:19: ERROR: Could not resolve "../../package.json"
```